{
	"version": 1730786430,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite3-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/cweimoet-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/tiledbackground3.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/tiledbackground4.png",
		"images/sprite22-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/tiledbackground5.png",
		"images/sprite25-sheet0.png",
		"images/duri3-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/duriiiii-sheet0.png",
		"images/coinpink2-sheet0.png",
		"images/sprite32-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/duri2-sheet0.png",
		"images/sprite36-sheet0.png",
		"images/zombieror-sheet0.png",
		"images/coin2-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/sprite37-sheet0.png",
		"images/sprite38-sheet0.png",
		"images/sprite39-sheet0.png",
		"images/sprite40-sheet0.png",
		"images/sprite42-sheet0.png",
		"images/sprite43-sheet0.png",
		"images/sprite29-sheet0.png",
		"images/coin333-sheet0.png",
		"images/sprite31-sheet0.png",
		"images/sprite46-sheet0.png",
		"images/sprite47-sheet0.png",
		"images/sprite48-sheet0.png",
		"images/sprite49-sheet0.png",
		"images/sprite50-sheet0.png",
		"images/sprite51-sheet0.png",
		"images/sprite52-sheet0.png",
		"images/sprite53-sheet0.png",
		"images/sprite54-sheet0.png",
		"images/sprite55-sheet0.png",
		"images/sprite55-sheet1.png",
		"images/sprite55-sheet2.png",
		"media/backsound game nabila.m4a",
		"media/backsound game nabila.ogg",
		"media/backsound finish.m4a",
		"media/backsound finish.ogg",
		"media/sound coin.m4a",
		"media/sound coin.ogg",
		"media/es kolkol.m4a",
		"media/es kolkol.ogg",
		"media/es kolkol finish.m4a",
		"media/es kolkol finish.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}